/*
 * (C) Copyright 2026 UCAR
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 */

#pragma once

#include <memory>
#include <string>
#include <unordered_set>
#include <vector>

#define ECKIT_TESTING_SELF_REGISTER_CASES 0

#include "eckit/config/LocalConfiguration.h"
#include "eckit/testing/Test.h"

#include "ioda/containers/FrameMetadata.h"
#include "ioda/containers/FrameRows.h"
#include "ioda/containers/IFrame.h"
#include "ioda/ioPool/IoPoolParameters.h"
#include "ioda/ObsDataIoParameters.h"
#include "ioda/reader/load/loadObs.hpp"

#include "oops/mpi/mpi.h"
#include "oops/runs/Test.h"
#include "oops/util/Logger.h"

namespace ioda {
namespace test {

// -----------------------------------------------------------------------------
// Verify the OSDF reader's variable-shape filter (keepNetcdfVarForOSDF) using a
// committed input file (ioda-data, generated by make_osdf_reader_keepvar.py) that
// holds one variable of each shape the filter must classify:
//   - MetaData/latitude          [Location]            -> kept (1D Location)
//   - MetaData/longitude         [Location]            -> kept (1D Location)
//   - ObsValue/brightnessTemp.   [Location, Channel]   -> kept (2D, expands to slices)
//   - ObsError/badLocLoc         [Location, Location]  -> rejected (no slice dimension)
//   - ObsError/badChanLoc        [Channel, Location]   -> rejected (first dim not Location)
void testKeepVarRejection() {
  // Build the obsdatain and io pool parameters pointing at the committed input file.
  eckit::LocalConfiguration obsDataInConfig;
  obsDataInConfig.set("engine.type", "H5File");
  obsDataInConfig.set("engine.obsfile", "Data/testinput_tier_1/osdf_reader_keepvar.nc4");
  ioda::ObsDataInParameters dataInParams;
  dataInParams.deserialize(obsDataInConfig);

  eckit::LocalConfiguration ioPoolConfig;
  ioPoolConfig.set("max pool size", 1);
  ioda::IoPool::IoPoolParameters ioPoolParams;
  ioPoolParams.validateAndDeserialize(ioPoolConfig);

  // Load through the real reader pipeline.
  std::unique_ptr<osdf::IFrame> testOsdf = std::make_unique<osdf::FrameRows>();
  osdf::FrameMetadata osdfMetadata;
  const eckit::mpi::Comm & commAll = oops::mpi::world();
  reader::loadObs(dataInParams, ioPoolParams, commAll, testOsdf, osdfMetadata);

  // Kept variables produce columns.
  EXPECT(testOsdf->hasColumn("MetaData/latitude"));
  EXPECT(testOsdf->hasColumn("MetaData/longitude"));
  EXPECT(testOsdf->hasColumn("ObsValue/brightnessTemperature_1"));
  EXPECT(testOsdf->hasColumn("ObsValue/brightnessTemperature_2"));
  EXPECT(testOsdf->hasColumn("ObsValue/brightnessTemperature_3"));

  // The [Location, Location] variable is rejected: neither a bare nor a suffixed column,
  // and it never registered "Location" as a (second) dimension.
  EXPECT(!testOsdf->hasColumn("ObsError/badLocLoc"));
  EXPECT(!testOsdf->hasColumn("ObsError/badLocLoc_0"));
  EXPECT(!osdfMetadata.hasDim("Location"));

  // The [Channel, Location] variable (first dim not Location) is also rejected.
  EXPECT(!testOsdf->hasColumn("ObsError/badChanLoc"));
  EXPECT(!testOsdf->hasColumn("ObsError/badChanLoc_0"));

  // Only the genuine 2D variable is tracked as a multi-slice variable.
  const std::unordered_set<std::string> multiSliceVars = osdfMetadata.getMultiSliceVars();
  EXPECT(multiSliceVars.count("ObsValue/brightnessTemperature") == 1);
  EXPECT(multiSliceVars.count("ObsError/badLocLoc") == 0);
  EXPECT(multiSliceVars.count("ObsError/badChanLoc") == 0);
}

// -----------------------------------------------------------------------------
class ReaderKeepVar : public oops::Test {
 public:
  ReaderKeepVar() {}
  virtual ~ReaderKeepVar() {}

 private:
  std::string testid() const override {return "test::ReaderKeepVar";}

  void register_tests() const override {
    std::vector<eckit::testing::Test>& ts = eckit::testing::specification();

    ts.emplace_back(CASE("ioda/ReaderKeepVar/testKeepVarRejection")
      { testKeepVarRejection(); });
  }

  void clear() const override {}
};

// -----------------------------------------------------------------------------

}  // namespace test
}  // namespace ioda
