#======================================================================
# Project settings
#======================================================================
branches:
  only:
    - develop

language: cpp

services:
  - docker

before_install:
  - date
  - REPO_SOURCE_DIR=${TRAVIS_BUILD_DIR}/jcsda/src_repo

#  create the same file structure on Travis VM and Docker container
  - mkdir -p ${TRAVIS_BUILD_DIR}/jcsda/src_repo
# echo branch info
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_BRANCH
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
#======================================================================
# Clone all repos
#======================================================================
 
#  checkout for the same branch name in ioda-bundle
  - git clone https://github.com/jcsda/ioda-bundle.git ${REPO_SOURCE_DIR}/ioda-bundle
  - cd ${REPO_SOURCE_DIR}/ioda-bundle
  - git checkout $BRANCH || echo "No branch named $BRANCH in ioda-bundle repo"
  - cd $REPO_SOURCE_DIR

#  checkout for the same branch name in oops
  - git clone https://github.com/jcsda/oops.git ${REPO_SOURCE_DIR}/ioda-bundle/oops
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/oops
  - git checkout $BRANCH || echo "No branch named $BRANCH in oops repo"
  - cd $REPO_SOURCE_DIR

#  clone the testing branch of ioda
  - git clone -b $BRANCH https://github.com/jcsda/ioda.git ${REPO_SOURCE_DIR}/ioda-bundle/ioda 

  - if [ "$BRANCH" = "develop" ];
    then export BRANCH_FORK="release-stable";
    else export BRANCH_FORK=$BRANCH;
    fi

#  checkout for the same branch name in fckit
  - git clone https://github.com/jcsda/fckit.git ${REPO_SOURCE_DIR}/ioda-bundle/fckit
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/fckit
  - git checkout $BRANCH_FORK || echo "No branch named $BRANCH in atlas repo"; git checkout release-stable
  - cd $REPO_SOURCE_DIR

#  checkout for the same branch name in atlas
  - git clone https://github.com/jcsda/atlas.git ${REPO_SOURCE_DIR}/ioda-bundle/atlas
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/atlas
  - git checkout $BRANCH_FORK || echo "No branch named $BRANCH in atlas repo"; git checkout release-stable
  - cd $REPO_SOURCE_DIR

#  do no switch to develop branch by removing 
#  develop UPDATE in CMakeLists.txt in ioda-bundle

  - cd ${REPO_SOURCE_DIR}/ioda-bundle
  - sed -i 's/BRANCH develop  UPDATE//' CMakeLists.txt
  - sed -i 's/BRANCH release-stable  UPDATE//' CMakeLists.txt

  - cat CMakeLists.txt
  - cd ${REPO_SOURCE_DIR}
  - ls ${REPO_SOURCE_DIR}
  - ls ${REPO_SOURCE_DIR}/ioda-bundle
  - find . -name \* -exec chmod 777 {} \;

#======================================================================
# get docker image
# FROM  jcsda/docker:latest
#======================================================================
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/ioda
  - date
  - cd CI
  - docker build -t jcsda/dockerl2 --build-arg=Dockerfile .  #Dockerfile handles ssh for mpi
  - date
  - docker images
# request codecov to detect CI environment to pass through to docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - echo $ci_env
  - docker run -d -t $ci_env --name jcsda_container -v ${REPO_SOURCE_DIR}/ioda-bundle:/jcsda/src_repo jcsda/dockerl2
  - docker ps -a
  - date

#======================================================================
# Here are the run steps
#======================================================================
script:
  - docker exec jcsda_container ls
  - docker exec jcsda_container bash -c 'cp -r /jcsda/.openmpi/ ~/' 
##  use cmake with flags to generate test coverage reports
  - date
  - docker exec jcsda_container bash -c 'cd /build_container && cmake -DCMAKE_MODULE_PATH=/usr/local/share/ecbuild/cmake/ -DCMAKE_BUILD_TYPE=Debug -DENABLE_GPROF=ON  /jcsda/src_repo'
  - date
  - docker exec jcsda_container bash -c 'cd /build_container/ioda && make -j4'
  - date
  - docker exec jcsda_container bash -c 'cd /build_container/ioda && ctest --output-on-failure'
  - date
#upload to codecov
  - docker exec jcsda_container bash -c 'cd /build_container/ioda && ls'
  - docker exec jcsda_container bash -c 'cd /build_container/ioda && bash <(curl -s https://codecov.io/bash) -t 3b511d7d-c15d-4ee5-8a1e-29c6d97d2032 -R /jcsda/src_repo/ioda/'

