#======================================================================
# Project settings
#======================================================================
branches:
  only:
    - develop

language: cpp

services:
  - docker

before_install:
  - date
  - REPO_SOURCE_DIR=${TRAVIS_BUILD_DIR}/jcsda/src_repo

#  create the same file structure on Travis VM and Docker container
  - mkdir -p ${TRAVIS_BUILD_DIR}/jcsda/src_repo
# echo branch info
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_BRANCH
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

#======================================================================
# Clone all repos
#======================================================================
#  clone the testing branch of ioda
  - git clone -b $BRANCH https://github.com/jcsda/ioda.git ${REPO_SOURCE_DIR}/ioda-bundle/ioda

#  checkout for the same branch name in oops
  - git clone https://github.com/jcsda/oops.git ${REPO_SOURCE_DIR}/ioda-bundle/oops
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/oops
  - git checkout $BRANCH || echo "No branch named $BRANCH in oops repo"
  - cd $REPO_SOURCE_DIR

#  checkout for the same branch name in ioda-engines
  - git clone https://github.com/jcsda/ioda-engines.git ${REPO_SOURCE_DIR}/ioda-bundle/ioda-engines
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/ioda-engines
  - git checkout $BRANCH || echo "No branch named $BRANCH in ioda-engines repo"
  - cd $REPO_SOURCE_DIR

  - if [ "$BRANCH" = "develop" ];
    then export BRANCH_FORK="release-stable";
    else export BRANCH_FORK=$BRANCH;
    fi

#  checkout for the same branch name in fckit
  - git clone https://github.com/jcsda/fckit.git ${REPO_SOURCE_DIR}/ioda-bundle/fckit
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/fckit
  - git checkout $BRANCH_FORK || echo "No branch named $BRANCH in atlas repo"; git checkout release-stable
  - cd $REPO_SOURCE_DIR

#  checkout for the same branch name in atlas
  - git clone https://github.com/jcsda/atlas.git ${REPO_SOURCE_DIR}/ioda-bundle/atlas
  - cd ${REPO_SOURCE_DIR}/ioda-bundle/atlas
  - git checkout $BRANCH_FORK || echo "No branch named $BRANCH in atlas repo"; git checkout release-stable
  - cd $REPO_SOURCE_DIR

#  move CMakeLists.txt
  - mv ${TRAVIS_BUILD_DIR}/CI/CMakeLists.txt ${REPO_SOURCE_DIR}/ioda-bundle

#======================================================================
# Pull docker image
#======================================================================
  - docker pull jcsda/docker-clang-mpich-dev
  - docker images

script:
  - docker run -d -t --name clang_container -v ${REPO_SOURCE_DIR}/ioda-bundle:/jcsda/src_repo jcsda/docker-clang-mpich-dev
  - docker exec clang_container bash -c 'ls /jcsda/src_repo'
  - docker exec clang_container bash -c 'mkdir /build_container'
  - docker exec clang_container bash -c 'cd /build_container && ecbuild /jcsda/src_repo'
  - docker exec clang_container bash -c 'cd /build_container/ioda && make -j4'
  - docker exec clang_container bash -c 'cd /build_container/ioda && ctest --output-on-failure'
