#!/bin/bash

odb_ref=$1
odb_test=$2
odc_exe=$3

$odc_exe compare "$odb_ref" "$odb_test"
CC=$?

if [[ $CC != 0 ]]; then
  txt_ref="testoutput/${odb_ref##*/}.1.txt"
  txt_test="testoutput/${odb_test##*/}.2.txt"
  $odc_exe ls "$odb_ref" -o "$txt_ref"
  $odc_exe ls "$odb_test" -o "$txt_test"
  diff "$txt_ref" "$txt_test"
fi

exit $CC
