#pragma once

// This file defines what appears on the Main Page of the documentation
// generated by doxygen. The file contains no code, and does not appear
// in any cpp include statement.
//
/*!
 * \mainpage Interface for Observational Data Access (IODA)
 *
 * IODA is the Interface for Observational Data Access. This is the component of JEDI that ingests and processes observational data for use with other JEDI components.
 */
